### ISSUE TITLE
Some thoughts

### ISSUE THREAD

**Issue by kuraga** [zensh/route-trie#13]
Hello, @zensh !

Could we restore the subject? (please!)
```js
trie.define('/a/(abc(cat|dog))')
```

Thanks!

**Comment by kuraga** [comment]
@zensh , ping...

**Comment by zensh** [comment]
What kind of url should be matched? Please give me some example.

**Comment by kuraga** [comment]
@zensh it's already given. Any pattern (regexp) matching without a name. E.g.:
```js
trie.define('/(abc|def)')
```
It has been removed in v2. I can make a PR...

**Comment by zensh** [comment]
@kuraga PR is welcome 😜

**Comment by kuraga** [comment]
@zensh No :-( Too difficult and breaks current logic.

But we also lost prefixes...
```js
trie.define('/prefix:path')
```
Would you accept a PR for prefixes?...

**Comment by kuraga** [comment]
Sorry. No.

**Comment by zensh** [comment]
@kuraga I think that prefixes are unnecessary
