### ISSUE TITLE
Some breaking change propositions

### ISSUE THREAD

**Issue by kuraga** [zensh/route-trie#7]
1) Move **public** properties  `node._nodeState.*` to `node.*`.

2) Get rid of `abc|def` patterns as they're just regular expressions: `(abc|def)`.

**Comment by zensh** [comment]
1. In my design `node` object is a clean object, people can mount anything in `node` object as they need. So all properties are on `node._nodeState`. Maybe some public properties should moved to `node`, which one?
2. Now regular pattern should always in bracket pair: `(regex)`, separated pattern `string|string` is different from regular pattern:
   
   **regular pattern**: trie.define('/(a|b+)/c') will match `'/a/c'`, `'/b/c'` and `'/bbbbbb/c'`
   **separated pattern**: trie.define('/a|b+/c') only match `'/a/c'` and `'/b+/c'`
   
   In this way API become more clear and definite

**Comment by kuraga** [comment]
I talked about `node._nodeState.pattern`. But I think you're right.
